<?php
namespace App\Repository;

use App\Entity\Book;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * @extends ServiceEntityRepository<Book>
 */
class BookRepository extends BaseRepository
{
    public function getClass(): string
    {
        return Book::class; // TODO: Change the autogenerated stub
    }

    /**
     * Exemple : Trouver tous les livres d'un auteur triés par date
     * @return Book[]
     */
    public function findByAuthorOrderedByDate(string $author): array
    {
        return $this->createQueryBuilder('b')
            ->andWhere('b.author = :author')
            ->setParameter('author', $author)
            ->orderBy('b.publishedAt', 'DESC')
            ->getQuery()
            ->getResult();
    }

}
