<?php
namespace App\Repository;

use App\Entity\Borrow;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * @extends ServiceEntityRepository<Borrow>
 *
 * @method Borrow|null find($id, $lockMode = null, $lockVersion = null)
 * @method Borrow|null findOneBy(array $criteria, array $orderBy = null)
 * @method Borrow[]    findAll()
 * @method Borrow[]    findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
class BorrowRepository extends BaseRepository
{
    public function getClass(): string
    {
        return Borrow::class; // TODO: Change the autogenerated stub
    }

    /**
     * Finds all current unreturned loans in the system.
     * * @return Borrow[]
     */
    public function findActiveLoans(): array
    {
        return $this->createQueryBuilder('l')
            ->andWhere('l.isActive = :active')
            ->setParameter('active', true)
            ->leftJoin('l.member', 'm')->addSelect('m') // Optimize query performance (Eager load)
            ->leftJoin('l.book', 'b')->addSelect('b')     // Prevent N+1 query issue
            ->orderBy('l.loanDate', 'DESC')
            ->getQuery()
            ->getResult();
    }

    /**
     *  Generic finder to retrieve loans matching dynamic criteria with eager loading.
     * @param array|null $criteria
     * @param array $orderBy
     * @param int|null $limit
     * @return array
     */
    public function findLoansByCriteria(?array $criteria, array $orderBy = ['loanDate' => 'DESC'], ?int $limit = null): array
    {
        //dd($criteria);
        $qb = $this->createQueryBuilder('l')
            ->leftJoin('l.member', 'm')->addSelect('m') // Eager load to avoid N+1 issues
            ->leftJoin('l.book', 'b')->addSelect('b');

        if (empty($criteria)) {
            $criteria = [];
        }
        $parameterIndex = 0;
        foreach ($criteria as $field => $value) {
            // If searching by member custom ID, route through the joined member alias
            if ($field === 'memberId') {
                $qb->andWhere('m.memberId = :param_' . $parameterIndex);
            } elseif ($field === 'bookId') {
                $qb->andWhere('b.bookId = :param_' . $parameterIndex);
            } else {
                // Standard entity fields (e.g., isActive, loanDate)
                $qb->andWhere(sprintf('l.%s = :param_%d', $field, $parameterIndex));
            }

            $qb->setParameter('param_' . $parameterIndex, $value);
            $parameterIndex++;
        }

        foreach ($orderBy as $sortField => $direction) {
            $qb->addOrderBy('l.' . $sortField, $direction);
        }

        if ($limit !== null) {
            $qb->setMaxResults($limit);
        }

        return $qb->getQuery()->getResult();
    }

    /**
     * Finds loans that have breached their returnDueDate without being returned.
     * * @return Borrow[]
     */
    public function findOverdueLoans(): array
    {
        return $this->createQueryBuilder('l')
            ->andWhere('l.isActive = :active')
            ->andWhere('l.returnDueDate < :now')
            ->setParameter('active', true)
            ->setParameter('now', new \DateTimeImmutable())
            ->leftJoin('l.member', 'm')->addSelect('m')
            ->leftJoin('l.book', 'b')->addSelect('b')
            ->orderBy('l.returnDueDate', 'ASC')
            ->getQuery()
            ->getResult();
    }

    /**
     * Counts how many items a specific member currently has checked out.
     * Useful for checking validation constraints before allowing a new loan.
     */
    public function countActiveLoansByMember(int $memberId): int
    {
        return (int) $this->createQueryBuilder('l')
            ->select('COUNT(l.id)')
            ->andWhere('l.member = :memberId')
            ->andWhere('l.isActive = :active')
            ->setParameter('memberId', $memberId)
            ->setParameter('active', true)
            ->getQuery()
            ->getSingleScalarResult();
    }

}
