<?php
namespace App\Repository;

use App\Dto\Transaction\TransactionDto;
use App\Entity\Transaction;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;

/**
 * @extends ServiceEntityRepository<Transaction>
 *
 * @method Transaction|null find($id, $lockMode = null, $lockVersion = null)
 * @method Transaction|null findOneBy(array $criteria, array $orderBy = null)
 * @method Transaction[]    findAll()
 * @method Transaction[]    findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
class TransactionRepository extends BaseRepository
{
    public function getClass(): string
    {
        return Transaction::class; // TODO: Change the autogenerated stub
    }


    /**
     * Recherche dynamique de transactions selon plusieurs critères
     *
     * @param array $criteria
     * @return array
     * @throws \DateMalformedStringException
     */
    public function findByCriteria(array $criteria): array
    {
        $qb = $this->createQueryBuilder('t')
            ->innerJoin('t.member', 'm')
            ->addSelect('m');

        $qb->select(sprintf(
            'NEW %s(
            t.transactionId,
            t.amount,
            m.memberId,
            t.currency,
            t.status,
            t.referenceId,
            t.paymentMethod,
            t.createdAt,
            m.name)',
            TransactionDto::class
        ));

        if (!empty($criteria['transactionId'])) {
            $qb->andWhere('t.transactionId = :transactionId')
                ->setParameter('transactionId', $criteria['transactionId']);
        }

        if (!empty($criteria['memberId'])) {
            $qb->andWhere('m.id = :memberId')
                ->setParameter('memberId', $criteria['memberId']);
        }

        if (!empty($criteria['status'])) {
            $qb->andWhere('t.status = :status')
                ->setParameter('status', $criteria['status']);
        }

        if (!empty($criteria['paymentMethod'])) {
            $qb->andWhere('t.paymentMethod = :paymentMethod')
                ->setParameter('paymentMethod', $criteria['paymentMethod']);
        }

        if (!empty($criteria['dateFrom'])) {
            $qb->andWhere('t.createdAt >= :dateFrom')
                ->setParameter('dateFrom', new \DateTimeImmutable($criteria['dateFrom']));
        }

        if (!empty($criteria['dateTo'])) {
            $qb->andWhere('t.createdAt <= :dateTo')
                ->setParameter('dateTo', new \DateTimeImmutable($criteria['dateTo']));
        }

        $qb->orderBy('t.createdAt', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
